CREATE TABLE "games" (
  "appid" integer PRIMARY KEY,
  "name" text NOT NULL,
  "is_free" boolean DEFAULT false,
  "release_date" date,
  "coming_soon" boolean DEFAULT false,
  "platforms_windows" boolean DEFAULT false,
  "platforms_mac" boolean DEFAULT false,
  "platforms_linux" boolean DEFAULT false,
  "metacritic_score" integer,
  "recommendations_total" integer,
  "required_age" integer DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "genres" (
  "genre_id" integer PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "tags" (
  "tag_id" integer PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "developers" (
  "developer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "publishers" (
  "publisher_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "category_id" integer PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "game_genres" (
  "appid" integer,
  "genre_id" integer,
  PRIMARY KEY ("appid", "genre_id")
);

CREATE TABLE "game_tags" (
  "appid" integer,
  "tag_id" integer,
  "votes" integer,
  PRIMARY KEY ("appid", "tag_id")
);

CREATE TABLE "game_developers" (
  "appid" integer,
  "developer_id" integer,
  PRIMARY KEY ("appid", "developer_id")
);

CREATE TABLE "game_publishers" (
  "appid" integer,
  "publisher_id" integer,
  PRIMARY KEY ("appid", "publisher_id")
);

CREATE TABLE "game_categories" (
  "appid" integer,
  "category_id" integer,
  PRIMARY KEY ("appid", "category_id")
);

CREATE TABLE "pricing_history" (
  "pricing_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appid" integer,
  "currency" varchar(10),
  "price_initial" integer,
  "price_final" integer,
  "discount_percent" integer DEFAULT 0,
  "snapshot_date" timestamp DEFAULT (now())
);

CREATE TABLE "player_stats" (
  "stat_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appid" integer,
  "current_players" integer,
  "peak_today" integer,
  "snapshot_time" timestamp DEFAULT (now())
);

CREATE TABLE "ownership_estimates" (
  "appid" integer,
  "snapshot_date" date,
  "owners_min" integer,
  "owners_max" integer,
  "avg_playtime_forever" integer,
  "avg_playtime_2weeks" integer,
  "median_playtime_forever" integer,
  "median_playtime_2weeks" integer,
  "ccu" integer,
  PRIMARY KEY ("appid", "snapshot_date")
);

CREATE INDEX ON "pricing_history" ("appid", "snapshot_date");

CREATE INDEX ON "player_stats" ("appid", "snapshot_time");

ALTER TABLE "game_genres" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");

ALTER TABLE "game_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("genre_id");

ALTER TABLE "game_tags" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");

ALTER TABLE "game_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("tag_id");

ALTER TABLE "game_developers" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");

ALTER TABLE "game_developers" ADD FOREIGN KEY ("developer_id") REFERENCES "developers" ("developer_id");

ALTER TABLE "game_publishers" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");

ALTER TABLE "game_publishers" ADD FOREIGN KEY ("publisher_id") REFERENCES "publishers" ("publisher_id");

ALTER TABLE "game_categories" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");

ALTER TABLE "game_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "pricing_history" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");

ALTER TABLE "player_stats" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");

ALTER TABLE "ownership_estimates" ADD FOREIGN KEY ("appid") REFERENCES "games" ("appid");
